development:
  spotify_client_id: <%= ENV['SPOTIFY_CLIENT_ID'] %>
  spotify_client_secret: <%= ENV['SPOTIFY_CLIENT_SECRET'] %>
test:
  spotify_client_id: <%= ENV['SPOTIFY_CLIENT_ID'] %>
  spotify_client_secret: <%= ENV['SPOTIFY_CLIENT_SECRET'] %>
production:
  spotify_client_id: <%= ENV['SPOTIFY_CLIENT_ID'] %>
  spotify_client_secret: <%= ENV['SPOTIFY_CLIENT_SECRET'] %>
